### ISSUE TITLE
what are the advantages of DWB planner?

### ISSUE THREAD

**Issue by bxc237** [locusrobotics/robot_navigation#48]
Hi,
I would like to know that comparing to the original DWA planner, what makes the DWB planner be a better option for the navigation stack? Thanks!

**Comment by airuchen** [comment]
Hi there, 
I found this comparison quite useful. You may want to give it a look.
[https://github.com/ros-planning/navigation2/blob/master/nav2_dwb_controller/README.md](url)

**Comment by ninamwa** [comment]
Hi. I am confused about this sentence from the link: DWB was meant to replace both the planners in the navigation repository and provides an implementation of both DWA and Trajectory Rollout.

Is DWB an improved version of DWA or is it a combination of DWA and Trajectory Rollout?

**Comment by DLu** [comment]
For the fullest comments, please check out [my talk here](https://vimeo.com/236487972)

In essence, DWB was written to replace and be backward compatible with `dwa_local_planner`, and since that package implemented algorithms equivalent to both DWA and trajectory rollout (I believe), DWB can do both as well.
